name: Build Container and Publish

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:

  push:
    # tags:
    #   - 'v*'
    #   - 'latest'
    paths:
      - 'Dockerfile'
      - '!README.md'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 938118244111.dkr.ecr.us-east-1.amazonaws.com/image-processing-repo
  IMAGE_TAG: ${{ github.ref_name }}

run-name: Building ${{ github.ref_name }} and publishing

jobs:

  build:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      image: ${{ env.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::938118244111:role/image-processing-repo-actions-role
          aws-region: us-east-1
          mask-aws-account-id: 'false'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker buildx build -f Dockerfile -t $ECR_REPOSITORY:$IMAGE_TAG --build-arg "IMAGE_TAG=$IMAGE_TAG" .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
